### ISSUE TITLE
Add CC-BY-4 license

### ISSUE THREAD

**Issue by kytrinyx** [exercism/legacy-docs#1]
UPDATE: we settled on choosing the Creative Commons Attribution 4.0 International License:

http://creativecommons.org/licenses/by/4.0/legalcode

-----

_original issue_:

Since the documentation is all text-based, I think it would make sense to have a creative commons license.

I don't know which one.

**Comment by rootulp** [comment]
I think [choosealicense](https://choosealicense.com/) might be helpful. From the [non-software](https://choosealicense.com/non-software/) section:
> Open source software licenses can be used for non-software works, and often are the best choice. This is particularly the case when the works in question can be edited and versioned as source, e.g., open source hardware designs. Choose an open source license.

**Comment by kytrinyx** [comment]
I looked through the licenses on choosalicense.com, but I don't think a software license is necessary for this. Looking at other content sites, for example https://opensource.guide, it's under a Creative Commons license (CC-BY-4) https://creativecommons.org/licenses/by/4.0/

**Comment by ErikSchierboom** [comment]
Well, I don't know much about content licenses, so I usually look at what other people do. The [Microsoft docs](https://github.com/dotnet/docs/blob/master/license.txt) use the Creative Commons Attribution 4.0
International License

> Documentation is licensed under the Creative Commons Attribution 4.0
International License (http://creativecommons.org/licenses/by/4.0/legalcode).

**Comment by kytrinyx** [comment]
The question I have with regards to which CC license to use, is whether or not we think that _commercial use_ is OK. I'm perfectly happy with people reproducing this for learning, informational, inspirational purposes, and while I can't imagine that anyone could find a way to make a buck off of documentation like this, I'm still wary of the idea.

**Comment by jtigger** [comment]
No need to leave open the possibility for commercial use, @kytrinyx.  I don't know licenses well at all, so I can't meaningfully contribute here.  I'm glad you're thinking about bits like this.

**Comment by markijbema** [comment]
It seems strange to restrict commercial use of the documentation, but not the product:
https://github.com/exercism/exercism.io/blob/master/LICENSE

So you can perfectly legal make a commercial clone of exercism, but you cannot use any documentation? This triggers my consistency radar.

(feel free to disregard my opinion, mostly lurking nowaydays ;) )

**Comment by kytrinyx** [comment]
Yeah, you're right.

I was thinking of this clause:

> The GNU Affero General Public License is designed specifically to
ensure that, in such cases, the modified source code becomes available
to the community.

Which doesn't restrict commercial activity, but does require that any changes you make are made available to the community.

Based on the current discussion I think CC-BY-4 is the right way to go.
