### ISSUE TITLE
Document bulk issue creation

### ISSUE THREAD

**Issue by kytrinyx** [exercism/legacy-docs#10]
We often want to do one of to things:

1. Submit a bunch of issues (one for each exercise) in a single repository
1. Submit a bunch of (identical) issues to a bunch of different repositories

For the second there are several scenarios:

- submit to all language tracks
- submit to all language tracks that implement a given exercise
- submit to all the repositories on Exercism (rare, but it happens. E.g.: recent probot/stale example)

We have some documentation about this in https://github.com/exercism/docs/blob/master/contributing-to-language-tracks/improving-consistency-across-tracks.md

We should have a single document about submitting multiple issues, and then link from it where we mention blazon.

**Comment by Insti** [comment]
I found this issue when wanting to make a new issue:

Remove blazon section from: https://github.com/exercism/docs/blob/master/contributing-to-language-tracks/improving-consistency-across-tracks.md

**Comment by kytrinyx** [comment]
Yepp, once we have this documentation we should do a search for `blazon` throughout the docs, and probably tighten up and update what we have to point to the new documentation.

**Comment by petertseng** [comment]
Issue body has link https://github.com/exercism/docs/blob/master/contributing-to-language-tracks/improving-consistency-across-tracks.md but that seem to be 404 now. But I think https://github.com/exercism/docs/blob/master/you-can-help/improve-exercise-metadata.md#evolving-exercises is its equivalent.
