### ISSUE TITLE
Document how to create a brand new exercise

### ISSUE THREAD

**Issue by kytrinyx** [exercism/legacy-docs#11]
We currently have some documentation about creating a completely new exercise in https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md#implementing-a-completely-new-exercise

We should extract this to a separate document in this repository, probably in the https://github.com/exercism/docs/tree/master/contributing-to-language-tracks directory, and flesh it out so that it reads as a consistent, complete document.

Then delete the contents from the x-common contributing guide.

**Comment by kytrinyx** [comment]
If you're interested in picking this one up _go for it_!

Please drop a line here so that other people don't double-up on the work.

Then open a pull request... it doesn't have to be done, it just needs to be a start. We can go from there. If you get stuck, holler, either here or in the support chat https://gitter.im/exercism/support

**Comment by acgillette** [comment]
I'm interested! I'll go ahead and take this if no one else is working on it.

**Comment by kytrinyx** [comment]
Awesome, thank you @acgillette! :sparkles:

**Comment by mfernest** [comment]
Too slow! Maybe there's another?

**Comment by kytrinyx** [comment]
@mfernest Yes! I'll write one up right now and ping you in it.

**Comment by kytrinyx** [comment]
@acgillette How are you getting on with this?

**Comment by acgillette** [comment]
@kytrinyx ack so sorry Katrina, it's been a little nuts at Ada and I lost track of this. I have the docs on my computer, I'll go ahead and finish them tomorrow :)

**Comment by kytrinyx** [comment]
That sounds great! Ping me if you get stuck, I'll be focusing on open source stuff all day tomorrow.

**Comment by acgillette** [comment]
I added a new file for the new exercises and c/p the current information for making a new track onto it. 

In terms of fleshing it out, I was wondering if there was anything specific you were looking for, or an area you'd like fleshed out.

**Comment by kytrinyx** [comment]
@acgillette This is great. Let's start with just adding it, getting that merged, and then flesh it out as a separate task.

How open are you to feedback about the process itself? There are a bunch of etiquette/best-practice type things that are much easier to learn by doing and getting feedback while doing than to go read gobs and gobs of documentation up front.

If you're feeling like "nah, I'm done, let's just get this merged" that's totally fine, but if you're open to some tweaks and pointers on the general open-sourcery of it all, then I'm happy to talk about that.

**Comment by acgillette** [comment]
I am very open to feedback! I would love any you'd be willing to give me :)

**Comment by kytrinyx** [comment]
awesome, incoming :-) :heart:

**Comment by kytrinyx** [comment]
Fixed in https://github.com/exercism/docs/pull/55
