### ISSUE TITLE
Wrong link on website

### ISSUE THREAD

**Issue by ReedCopsey** [exercism/legacy-docs#111]
This page: http://www.exercism.io/languages/fsharp/resources

Currently links to `fpchat.com`.  However, that is no longer correct for the FP slack workspace. The new link is: `https://fpchat-invite.herokuapp.com/`

**Comment by coriolinus** [comment]
This issue should be moved to the [fsharp track repository](https://github.com/exercism/fsharp/issues).

**Comment by ReedCopsey** [comment]
Done. Thanks - https://github.com/exercism/fsharp/issues/462
