### ISSUE TITLE
Is unlocked-by always required for non-core exercises?

### ISSUE THREAD

**Issue by tejasbubane** [exercism/legacy-docs#113]
Came across this while changing the config to configlet 3.8.0 in https://github.com/exercism/javascript/issues/527

The [config spec](https://github.com/exercism/docs/blob/master/language-tracks/configuration/exercises.md#unlocked-by) says:

> All optional exercises should be unlocked by one of the core exercises.

This made me think that all optionals should have this property - later found out that tracks have kept it null at many places. eg. [ruby config](https://github.com/exercism/ruby/blob/master/config.json). Also the latest version of configlet allows having null values. 

Should `unlocked-by` be a required property? If not can we mention so in the spec?

**Comment by tleen** [comment]
The docs may need to be updated. `core:false` and `unlocked_by: null` indicate a bonus exercise. One that is available at the start of the track in case users want to try another exercise besides core right away. I believe this is still the case.

**Comment by kytrinyx** [comment]
> I believe this is still the case.

Yepp, that's still the case.
