### ISSUE TITLE
Document how to configure a language track

### ISSUE THREAD

**Issue by kytrinyx** [exercism/legacy-docs#12]
The `config.json` file has a number of options, and is kind of sort of referenced and halfway explained in a number of different places:

- The [x-common contributing guide][common-contributing]
- The "how to contribute language tracks" [document in the docs repo][docs-contributing]
- The [launch checklist][checklist] that gets added as the first issue to new language tracks

[common-contributing]:  https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md
[docs-contributing]: https://github.com/exercism/docs/blob/e87397653388ebbd795e72f07b9972c18295ca5d/contributing-to-language-tracks/README.md
[checklist]: https://github.com/exercism/request-new-language-track/blob/f743bbcba92658285e4c4a5883acee503a62ed42/CHECKLIST

We should create a `language-tracks/configuration/README.md` that documents the `config.json` file fully.

Remember to include the `test_pattern`, `ignore_pattern`, and `solution_pattern` keys.

There's also a `gitter` key.

As of https://github.com/exercism/meta/issues/3 there is no longer an "ignore" key in the config.json.

**Comment by Insti** [comment]
`config.json` is used by https://github.com/exercism/trackler 

The section in the [x-common contributing guide](https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md#useful-tidbits) looks like a good starting point.

**Comment by kytrinyx** [comment]
note: `config.json` is also used by https://github.com/exercism/configlet

**Comment by kytrinyx** [comment]
Once this documentation exists, we need to update the README in https://github.com/exercism/configlet to point to it.
