### ISSUE TITLE
I Can Read C++ and Java But I Can’t Read Smalltalk

### ISSUE THREAD

**Issue by bencoman** [exercism/legacy-docs#120]
Should we reference or intermix parts of this document (which I love) ?
[readingSmalltalk.pdf](https://github.com/exercism/docs/files/2276414/readingSmalltalk.pdf)

**Comment by macta** [comment]
Oh yes - that should be near the top of the learning.md but possibly in the installation guide too.

**Comment by macta** [comment]
Is that the best url for it?

**Comment by bencoman** [comment]
If you search on the title you'll find a scattering of places its hosted, but we've no control over them. 
That url is the file I uploaded to the issue tracker.  I uploaded the whole thing for discussion,
but I think its too long for a newcomer to absorb in one go.  I think first 4 pages are critical should be
shown right at the start, with a tiny extra bit only about period as a statement separator.

Introduce semicolons later. And we only need setters/getters when we start needing instance variables.
The first few exercises seem not to.  Same for collections and sequencing - when they are needed.

**Comment by bencoman** [comment]
Whoops. Was this the right repo for this?  I thought I put it in the 'pharo' repo. 
(Edit: And is there some way to get it moved there?)

**Comment by ErikSchierboom** [comment]
I think this is indeed the wrong repo :)

**Comment by kytrinyx** [comment]
I can move it :)

**Comment by kytrinyx** [comment]
_This issue has been imported to the https://github.com/exercism/pharo repository._
