### ISSUE TITLE
Maintainer docs point to archived repo

### ISSUE THREAD

**Issue by pgaspar** [exercism/legacy-docs#123]
The [README.md](https://github.com/exercism/docs/blob/master/maintaining-a-track/README.md) file under `maintaining-a-track` points to the [exercism/discussions](https://github.com/exercism/discussions) repo which has been archived.

**Comment by rpottsoh** [comment]
Should probably point to [exercism/exercism/issues](https://github.com/exercism/exercism/issues).  Line 90 of the [README.md](https://github.com/exercism/docs/blob/master/maintaining-a-track/README.md) would need to be updated.
