### ISSUE TITLE
Capture standard operating procedures in a runbook

### ISSUE THREAD

**Issue by jtigger** [exercism/legacy-docs#13]
There are things that we do to keep the lights on.  Is this the place to document those things too?

- availability indicators (API 200s, website 200s)
- availability objectives (e.g. 99% (~7hrs/mo))
- monitoring (both indicators and logs)
- packaging and deploying
  - building all of exercism.io, step-by-step
  - deployment process, step-by-step
- alerting
- backups and restores

**Comment by kytrinyx** [comment]
> Is this the place to document those things too?

💯 This is absolutely the place to capture this.

We're going to need a new directory, perhaps `site-operations`?
