### ISSUE TITLE
Docs issue: Unable to find "contributing" section in sidebar

### ISSUE THREAD

**Issue by sameer-j** [exercism/legacy-docs#131]
Trying to follow the instruction given below, but not able to find the said location of contirbution in the sidebar.
https://github.com/exercism/docs/blob/master/you-can-help/implement-an-exercise-from-specification.md#finding-an-exercise-to-port

Please the update the doc if required or someone can help me understand this.

**Comment by SleeplessByte** [comment]
You're right. That link no longer exists.

Just for my information: For which track were you trying to do this?

**Comment by sameer-j** [comment]
Python. I am trying to contribute by implementing paasio exercise and was looking for a track to port this from.
