### ISSUE TITLE
Mentor comment box missing tabbing 

### ISSUE THREAD

**Issue by Qazzquimby** [exercism/legacy-docs#136]
When I'm mentoring I often want to write some code in a block, and need to mash space to add indentation.

There are tools to facilitate this
http://julianlam.github.io/tabIndent.js/
http://jakiestfu.github.io/Behave.js/

If I integrated something like that, would that be an appreciated pull request?

**Comment by neenjaw** [comment]
@ihid or @ErikSchierboom can probably give you insight on this.

**Comment by ErikSchierboom** [comment]
@Qazzquimby Thanks for the suggestion! We don't take PR's for the website at the moment, as we're hard at work on the v3 version of the website. We'll consider implementing your suggestion for the v3 website!
