### ISSUE TITLE
Document the anatomy of a track

### ISSUE THREAD

**Issue by kytrinyx** [exercism/legacy-docs#22]
There is a slightly outdated section in the x-common contributing document about track anatomy: https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md#track-anatomy

A great first step would be to move this into this repository. It should go into `/language-tracks/README.md`

A nice plus would be to delete the bulk of the explanation  about the `docs/` directory, and instead link to the https://github.com/exercism/docs/blob/master/maintaining-a-track/writing-documentation.md document.

Then open a PR that delete's the section from the problem-specifications contributing document.

Note: we'll need to add a section about the `.meta/` directory.

**Comment by kytrinyx** [comment]
@mfernest this is a bit more straight forward than the "start a language track" one. Take your pick!

**Comment by mfernest** [comment]
@kytrinyx  I'll take both unless someone wants the other for their very own.

**Comment by kytrinyx** [comment]
I made plenty... probably more than enough for everyone at this point.

**Comment by kytrinyx** [comment]
@mfernest Are you doing alright with this one?

**Comment by kytrinyx** [comment]
It's been a month. I'm going to go ahead and unclaim this.
