### ISSUE TITLE
Document pull request guidelines

### ISSUE THREAD

**Issue by kytrinyx** [exercism/legacy-docs#24]
These are currently documented in https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md#pull-request-guidelines

They should be moved into the https://github.com/exercism/docs/tree/master/contributing-to-language-tracks directory in this repository.

That will take two pull requests. One in this repository to add the new file, and one in the https://github.com/exercism/x-common repository to delete the copy that was moved from the CONTRIBUTING.md file.

**Comment by aos** [comment]
Hi @kytrinyx ! Thank you for exercism! I will work on this one today/tomorrow

**Comment by kytrinyx** [comment]
Fixed in #43
