### ISSUE TITLE
Document exercise versioning

### ISSUE THREAD

**Issue by kytrinyx** [exercism/legacy-docs#25]
These are currently documented in
https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md#exercise-versioning

They should be moved into the https://github.com/exercism/docs/tree/master/maintaining-a-track directory in this repository.

That will take two pull requests. One in this repository to add the new file, and one in the https://github.com/exercism/x-common repository to delete the copy that was moved from the CONTRIBUTING.md file.

**Comment by eclecticjohny** [comment]
I would like to try and submit a PR for this issue.

**Comment by kytrinyx** [comment]
Thank you @eclecticjohny!
