### ISSUE TITLE
Document the anatomy of an exercise

### ISSUE THREAD

**Issue by kytrinyx** [exercism/legacy-docs#26]
These are currently documented in https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md#anatomy-of-an-exercise

They should be moved into the https://github.com/exercism/docs/tree/master/maintaining-a-track directory in this repository.

That will take two pull requests. One in this repository to add the new file, and one in the https://github.com/exercism/x-common repository to delete the copy that was moved from the CONTRIBUTING.md file.

**Comment by mfernest** [comment]
Put me in, coach. I can do it!

**Comment by kytrinyx** [comment]
It's yours :) Holler if you need anything.

**Comment by kytrinyx** [comment]
@mfernest just checking in to make sure you're doing alright here. You still good to go on this one?

**Comment by kytrinyx** [comment]
@mfernest Since I've not heard back on this I'm going to go ahead and put it back in the pool of up for grabs issues.

**Comment by aos** [comment]
Hi @kytrinyx. If no one has picked this up by Sunday, I'll do it. 🙂

**Comment by kytrinyx** [comment]
Sounds like a plan :)

**Comment by petertseng** [comment]
The next step would be to fill out all the TODOs in the https://github.com/exercism/docs/blob/master/language-tracks/exercises/anatomy/README.md! There should be an issue for it so that people know it is still something to be done.
