### ISSUE TITLE
Document track level linting with configlet

### ISSUE THREAD

**Issue by kytrinyx** [exercism/legacy-docs#27]
These are currently documented in
https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md#track-level-linting-with-configlet

They should be moved into the https://github.com/exercism/docs/tree/master/maintaining-a-track directory in this repository.

That will take two pull requests. One in this repository to add the new file, and one in the https://github.com/exercism/x-common repository to delete the copy that was moved from the CONTRIBUTING.md file.

**Comment by aos** [comment]
I'll work on this one as well if no one has picked it up

**Comment by kytrinyx** [comment]
Completed in #44 and exercism/x-common #817

@aosdab - one new trick to learn: when you open a pull request, you can add a comment in the body of the pull request comment that will automatically close the issue when the pull request gets merged: https://github.com/blog/1506-closing-issues-via-pull-requests

**Comment by aos** [comment]
Awesome. Thank you for that! I would have never done that if you didn't tell me. Will start in the future. :-)
