### ISSUE TITLE
Document how to update exercise test suites

### ISSUE THREAD

**Issue by kytrinyx** [exercism/legacy-docs#28]
These are currently documented in
https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md#updating-an-exercise-test-suite

They should be moved into the https://github.com/exercism/docs/tree/master/you-can-help directory in this repository. A good name would be `update-exercise-test-suites.md`

That will take two pull requests. One in this repository to add the new file, and one in the https://github.com/exercism/x-common repository to delete the copy that was moved from the CONTRIBUTING.md file.

**Comment by abdulhannanali** [comment]
@kytrinyx Would love to work it

**Comment by kytrinyx** [comment]
@abdulhannanali It's yours!

**Comment by kytrinyx** [comment]
It's been a month, I'm going to go ahead and reset this one to up for grabs.

**Comment by abdulhannanali** [comment]
@kytrinyx Sorry for this delay forgot about it. I am going to work on this first thing tomorrow.

**Comment by kytrinyx** [comment]
@abdulhannanali Ok, cool. I'm changing the status back to claimed for you.
