### ISSUE TITLE
Add documentation about "what doesn't make a good track"

### ISSUE THREAD

**Issue by kytrinyx** [exercism/legacy-docs#56]
Only the newsletter has this: http://tinyletter.com/exercism/letters/what-exercism-is-and-isn-t
... we need to add it somewhere, but not sure where.

I think it probably needs its own file, probably within the `about/` directory. Maybe call it `in-scope-out-of-scope.md`

**Comment by OrthoDex** [comment]
Hey @kytrinyx ! I would like to take this up if it's alright.

**Comment by kytrinyx** [comment]
Hi @OrthoDex, yes! That would be wonderful. Thank you 🌻
