### ISSUE TITLE
Canonical track maintenance contributing guide?

### ISSUE THREAD

**Issue by stkent** [exercism/legacy-docs#61]
We have:

https://github.com/exercism/problem-specifications/blob/master/CONTRIBUTING.md

and

https://github.com/exercism/docs/tree/master/contributing-to-language-tracks

which cover similar ground but were obviously written separately. Is one of these considering more definitive than the other moving forward? Which resource should tracks be pointing interested newcomers to?

**Comment by kytrinyx** [comment]
The docs repo is where I'd like to point everyone to. I have open issues here to move things from the problem-specifications Contributing guide.

**Comment by stkent** [comment]
Roger that, thanks! Wasn't sure if that also applied to repo-specific files that are treated specially by GitHub, like READMEs, CONTRIBUTING, etc.

**Comment by kytrinyx** [comment]
Yeah, each repo will still have a README and Contributing file that is relevant to that repo. All the project-wide stuff should be in the docs repo, though.
