### ISSUE TITLE
Add documentation about track contributing documentation

### ISSUE THREAD

**Issue by kytrinyx** [exercism/legacy-docs#68]
add file: `/language-tracks/documentation/for-contributors.md`

Talk about:

* track readme
* contributing guide
* pull request / issue templates

**Comment by masters3d** [comment]
Where is the info about UUID?

**Comment by kytrinyx** [comment]
It's in the language tracks documentation (https://github.com/exercism/docs/tree/master/language-tracks) under configuration > exercises: https://github.com/exercism/docs/blob/master/language-tracks/configuration/exercises.md

**Comment by masters3d** [comment]
@kytrinyx  Can I add a link of those files to the readme.md? Or would that break the website?

**Comment by kytrinyx** [comment]
Let's wait until we get #100 sorted out—we should probably have several things linked in the README.
