### ISSUE TITLE
first-exercise.md: ends abruptly

### ISSUE THREAD

**Issue by rpottsoh** [exercism/legacy-docs#86]
The last sentence is not complete in [first-exercise.md](https://github.com/exercism/docs/blob/master/language-tracks/launch/first-exercise.md).

**Comment by kytrinyx** [comment]
Oh, wow. I think I ran out of steam and didn't notice. I'll take another stab at this one when my brain is fresh.

**Comment by rpottsoh** [comment]
@kytrinyx it appears as though you were going to describe what `configlet fmt .` would be doing for the track maintainer as part exercise configuration.  I can probably fix that, but I don't know what else you may want to say on the subject as a whole.  At least I can help out tidying up the end of the document for the time being.

**Comment by kytrinyx** [comment]
If you just make it end that would be wonderful. At some point I'm sure I'll have more to say 😅 but I have no idea what I was thinking at that moment.
