### ISSUE TITLE
Finish incomplete sentence

### ISSUE THREAD

**Issue by Stargator** [exercism/legacy-docs#94]
The [implementing first exercise](https://github.com/exercism/docs/blob/master/language-tracks/launch/first-exercise.md#exercise-configuration) doc has an unfinished statement at the end.

> Once `lint` is happy, run `configlet fmt .`, which

**Comment by ilya-khadykin** [comment]
This one is related to #86

**Comment by rpottsoh** [comment]
I am preparing a PR to correct the problem.
